Command commit - branch - checkout
JustSeenn/JGIT pull request #64
Opened 2023-03-06 22:14 UTC by damedomey

Limite du checkout : Ne restore pas le state dans les fichiers. Je vais bosser dessus après.
Test branch : :ok: 
Test checkout : :ok: mais partiel 
Test commit : pas pour le moment

2023-03-07 07:10 UTC, fayssalElAnsari commented on src/main/java/fr/uca/jgit/command/Branch.java
> +            String head = RepositoryController.getHeadHash();
on doit utiliser WorkingDirectory au lieu de RepositoryController

2023-03-07 07:12 UTC, fayssalElAnsari commented on src/main/java/fr/uca/jgit/controller/RepositoryController.java
>              BufferedReader reader = new BufferedReader(new FileReader(WorkingDirectory.getInstance().getPath(".jgit", "HEAD").toString()));
a mettre dans WD?

2023-03-07 07:13 UTC, fayssalElAnsari commented on src/test/resources/features/Branch.feature
> +    Then the result is "Switched to a new branch 'dev'"
cést mieux de mettre "executes" ou "runs the command" au lieu de "wants to execute"

2023-03-07 07:16 UTC, damedomey commented on src/main/java/fr/uca/jgit/controller/RepositoryController.java
>              BufferedReader reader = new BufferedReader(new FileReader(WorkingDirectory.getInstance().getPath(".jgit", "HEAD").toString()));
Ah oui ! Je vais le déplacer vers wd. C'est mieux.

2023-03-09 06:28 UTC, damedomey commented on src/main/java/fr/uca/jgit/controller/RepositoryController.java
>              BufferedReader reader = new BufferedReader(new FileReader(WorkingDirectory.getInstance().getPath(".jgit", "HEAD").toString()));
C'est fait

2023-03-12 08:08 UTC, damedomey commented on JGitClient/src/main/java/fr/uca/jgit/command/StateCommit.java
> +			if (systemFile.isFile() && systemFile.getName().endsWith(".txt")) {
Voici la cause des tas de messages d'erreurs dans la console. Un fichier text n'est pas forcément avec l'extension **.txt**. Se baser sur le mime du fichier ou un autre truc serait mieux.

2023-03-12 08:09 UTC, damedomey commented on JGitClient/src/main/java/fr/uca/jgit/command/StateCommit.java
> +			if (systemFile.isFile() && systemFile.getName().endsWith(".txt")) {
@fayssalElAnsari

2023-03-13 10:35 UTC, JustSeenn requested changes

2023-03-13 10:35 UTC, JustSeenn commented on JGitClient/src/main/java/fr/uca/jgit/command/Branch.java
> +            // System.out.println("No branch list file found");
Normal que ce soit commenté ?

2023-03-13 10:35 UTC, JustSeenn commented on JGitClient/src/main/java/fr/uca/jgit/command/Branch.java
> +        String branchName = args[0];
Petit check si args.length() > 0

2023-03-13 10:35 UTC, JustSeenn commented on JGitClient/src/main/java/fr/uca/jgit/command/StateCommit.java
> +		}
Je trouve qu'il y a trop de commentaire inutile. Au-dessus de la méthode, c'est bien, mais sur chaque ligne ça fait lourd

2023-03-13 10:35 UTC, JustSeenn commented on JGitClient/src/test/java/fr/uca/jgit/model/CommitStepdefs.java
> +			Path parentPath = Path.of(".tmp/" + filePath.getParent());
Pourquoi tmp et pas tmpFiles comme les autres tests ?
Tu peux utiliser le WorkingDirectory pour ne pas avoir de problèmes de chemin

2023-03-13 10:35 UTC, JustSeenn commented on JGitClient/src/test/java/fr/uca/jgit/command/CheckoutStepDefs.java
> +            // It's mean, the user don't check out any branch before
This mean, the user don't check out any branch before*.

2023-03-13 10:35 UTC, JustSeenn commented on JGitClient/src/test/java/fr/uca/jgit/command/CheckoutStepDefs.java
> +            // It's mean, the user don't check out any branch before
This mean, the user don't check out any branch before*.

2023-03-13 10:35 UTC, JustSeenn commented on JGitClient/src/test/java/fr/uca/jgit/command/CheckoutStepDefs.java
> +        // Do nothing
À faire, sinon les tests ne sont pas valides

2023-03-13 10:46 UTC, hebabz reviewed
Est-ce "branch_list" est un fichier qui se trouvera définitivement dans ".jgit" ? Mon test pour "git init" vérifie que chaque fichier ou dossier présent dans ".jgit" a été identifié (donc HEAD, objects, et logs), mais le test retourne une erreur actuellement car "branch_list" est présent et le step ne reconnait pas ce fichier. Je dois modifier mon test ou t'as oublié de reset le repository ?

2023-03-13 10:46 UTC, hebabz commented on JGitClient/src/test/java/fr/uca/jgit/command/CommandStepDefs.java
> +    @When("the user execute the command {string}")
Alors il va me falloir une justification de pk il y a 2 when identiques pointant vers la même fonction (d'ailleurs ça marche vraiment ? 😮 ) pour une même fonction, au lieu de simplement réécrire la feature reliée pour qu'elle ait la même orthographe

2023-03-13 10:53 UTC, damedomey commented on JGitClient/src/test/java/fr/uca/jgit/command/CommandStepDefs.java
> +    @When("the user execute the command {string}")
J'ai oublié de le souligner. Dans les commentaires plus haut, @fayssalElAnsari a demandé de modifier le texte du when. Ce que j'ai fait. J'ai laissé l'ancien également parceque d'autres l'avaient utilisé dans leurs tests (je crois). Donc c'est juste pour que les tests utilisant l'ancienne version marchent toujours. L'idée est que tous ceux qui l'avaient utilisé passent au nouveau texte et qu'on supprime le when avec **want** dans la phrase

2023-03-13 10:55 UTC, hebabz commented on JGitClient/src/test/java/fr/uca/jgit/command/CommandStepDefs.java
> +    @When("the user execute the command {string}")
Aaaah ok je t'invite à ajouter un commentaire parlant de ça juste à côté comme ça quand on nettoiera le projet on corrigera tout d'un coup !

2023-03-13 10:59 UTC, damedomey commented on JGitClient/src/test/java/fr/uca/jgit/command/CommandStepDefs.java
> +    @When("the user execute the command {string}")
En ce qui concerne branch_list, oui, il était censé rester là indéfiniment. Mais s'il fait échouer tes tests, je peux le deplacer vers logs même le mieux aurait été de le laisser dans jgit. Je ne sais pas ce que t'en penses.

2023-03-13 11:03 UTC, damedomey commented on JGitClient/src/main/java/fr/uca/jgit/command/Branch.java
> +            // System.out.println("No branch list file found");
Oui, mais je vais supprimer le commentaire. Cette fonction est appelé de nombreuses fois et le fichier branch_list n'existe pas par exemple au début du projet quand on ne créé pas de branche.
Il n'y aura rien dans le catch

2023-03-13 11:06 UTC, damedomey commented on JGitClient/src/test/java/fr/uca/jgit/command/CheckoutStepDefs.java
> +        // Do nothing
Je pense que je vais plutôt le retirer. C'était juste pour dire ce que la commande renvoie dans la console. Ce n'est pas un test en soit. Les tests sont souvent dans la ligne qui suit dans le scénario.

2023-03-13 11:26 UTC, hebabz commented on JGitClient/src/test/java/fr/uca/jgit/command/CommandStepDefs.java
> +    @When("the user execute the command {string}")
Nah je pense que tu peux ajouter un truc simple dans le test "controller/directory/InitStepdefs.java"

tu vois dans "a_new_jgit_repository_is_created()" ? T'as juste à continuer le else if avec
`else if(file.getName().equals("branch_list")){
                assertTrue(file.isDirectory());
            }`

et quand tu lances mvn test t'as un test échoué en moins.

2023-03-13 13:03 UTC, hebabz commented on JGitClient/src/test/java/fr/uca/jgit/command/CommandStepDefs.java
> +    @When("the user execute the command {string}")
OULA J'AI DIT UNE BÊTISE c'est file.isFile()

2023-03-14 07:58 UTC, JustSeenn approved these changes

2023-03-14 08:58 UTC, merged